services:
    api:
      image: mymicroservice
      build: 
        context: .
      ports:
        - "3000:80"
      networks:
        - micronet
      environment:
        - ASPNETCORE_URLS=http://+:80
      depends_on:
        - sqlserver

    sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      restart: always
      environment: 
        SA_PASSWORD: "VeryComplex123Password"
        ACCEPT_EULA: "Y"
      ports:
        - "1433:1433"
      networks:
        - micronet
      volumes:
        - sqlserver_data:/var/opt/mssql/data

volumes:
  sqlserver_data:

networks:
  micronet:
    driver: bridge